# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='not\xedcia')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2017, 4, 14, 22, 29, 25, 656226, tzinfo=utc), verbose_name='data de cria\xe7\xe3o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
    ]
