# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cria\xe7\xe3o'),
        ),
    ]
