# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20170414_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name='data de cria\xe7\xe3o'),
        ),
    ]
