# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20170414_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('data_criacao', 'ativo'), 'verbose_name': 'not\xedcia', 'verbose_name_plural': 'not\xedcias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateField(auto_now=True, verbose_name='data de cria\xe7\xe3o'),
        ),
    ]
