# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('ERRO', 'Erro'), ('CRITICA', 'Cr\xedtica'), ('SUGESTAO', 'Sugest\xe3o')], default='ERRO', max_length=128, verbose_name='assunto')),
                ('mensagem', models.TextField(max_length=512)),
                ('data_adicao', models.DateTimeField(auto_now=True, verbose_name='data de adi\xe7\xe3o')),
                ('resolvido', models.BooleanField(default=False, verbose_name='resolvido?')),
            ],
            options={
                'ordering': ('data_adicao', 'resolvido'),
                'verbose_name': 'relatorio',
                'verbose_name_plural': 'relatorios',
            },
        ),
    ]
