# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='nome')),
                ('em_abastecimento', models.BooleanField(default=False, verbose_name='Em abastecimento?')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='data de in\xedcio')),
                ('data_fim', models.DateField(blank=True, verbose_name='data de fim')),
                ('qts_abastecimentos', models.PositiveIntegerField(verbose_name='resid\xeancias com \xe1gua')),
            ],
            options={
                'ordering': ('data_inicio', 'data_fim'),
                'verbose_name': 'hist\xf3rico',
                'verbose_name_plural': 'hist\xf3ricos',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='nome')),
                ('em_abastecimento', models.BooleanField(default=False, verbose_name='Em abastecimento?')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
            },
        ),
        migrations.AddField(
            model_name='historico',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_abastecimento.Setor'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_abastecimento.Setor'),
        ),
    ]
