# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='qts_abastecimentos',
            field=models.PositiveIntegerField(default=0, verbose_name='resid\xeancias com \xe1gua'),
        ),
    ]
